#pragma once

#define VAR_NAME_LEN 128 // max len functor

#define SUCCESS 1
#define FAILURE -1

// in no particular order

#define FILE_NOT_FOUND -1
#define PARSE_ERROR -2
#define UNBALANCED_PAR -3
#define PARSER_ERROR -4
#define UNBALANCED_PARENTHESES_ERROR -5
#define UNKNOWN_CONTENT -6
#define REALLOC_ERROR_EXIT -7
#define MODE_ERROR -8
#define UNKOWN_FUNCTOR -9
#define CONVERSION_STRING_INT_FAILURE -10
#define LINE_NOT_FOUND -11
#define INDEX_NOT_FOUND -12
#define PREDICATE_NOT_FOUND -13
#define PRINT_HELP -14
#define MISSING_QUERY -15
#define MISSING_FILENAME -16
#define REVERSE_FAILURE -17
#define APPEND_FAILURE -18
#define EXPECTED_NUMBER -19
#define UNKNOWN_FUNCTOR -20
#define NTH_ERROR -21
#define TERM_NOT_FOUND -22
#define COMMAND_ERROR -22
#define MISSING_QUOTE -23
#define CHECK_ARITY_ERROR -24
#define OUT_OF_RANGE -25